# Generated by Django 4.0 on 2023-04-04 22:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reviews", "0002_auto_20230403_2308"),
        ("reviews", "0002_initial"),
    ]

    operations = []
